import fs from 'fs'
import path from 'path'
import type { SkillMarkdown, HealthScore, SkillScanResult } from './types'

export function writeOutputs(
  projectPath: string,
  skills: SkillMarkdown[],
  healthScore: HealthScore & { summary: string },
  results: SkillScanResult[],
  outputDir?: string
): string {
  const aiContextDir = outputDir ?? path.join(projectPath, 'ai-context', 'skills')
  fs.mkdirSync(aiContextDir, { recursive: true })

  // ── Write each skill.md ───────────────────────────────────────────────────
  for (const skill of skills) {
    const filePath = path.join(aiContextDir, skill.filename)
    fs.writeFileSync(filePath, skill.content, 'utf-8')
  }

  // ── Write gap report ──────────────────────────────────────────────────────
  const gapReport = buildGapReport(results, healthScore)
  const reportPath = path.join(aiContextDir, 'project-health-report.md')
  fs.writeFileSync(reportPath, gapReport, 'utf-8')

  // ── Write / update CLAUDE.md ──────────────────────────────────────────────
  updateClaudeMd(projectPath, aiContextDir, skills)

  return aiContextDir
}

function buildGapReport(
  results: SkillScanResult[],
  healthScore: HealthScore & { summary: string }
): string {
  const allFindings = results.flatMap(r => r.findings)
  const criticals = allFindings.filter(f => f.severity === 'critical')
  const warnings = allFindings.filter(f => f.severity === 'warning')
  const date = new Date().toISOString().split('T')[0]

  const gradeColor = healthScore.grade === 'A' ? '🟢'
    : healthScore.grade === 'B' ? '🟡'
    : healthScore.grade === 'C' ? '🟠'
    : '🔴'

  const lines: string[] = [
    `# AppProbe — Project Health Report`,
    ``,
    `> Generated: ${date}`,
    ``,
    `## Health score`,
    ``,
    `| Overall | Grade |`,
    `|---------|-------|`,
    `| **${healthScore.overall}/100** | ${gradeColor} **${healthScore.grade}** |`,
    ``,
    `${healthScore.summary}`,
    ``,
    `### Score by skill`,
    ``,
    `| Skill | Score |`,
    `|-------|-------|`,
    ...Object.entries(healthScore.breakdown).map(
      ([skill, score]) => `| ${skill} | ${score}/100 |`
    ),
    ``,
  ]

  if (criticals.length > 0) {
    lines.push(`## 🔴 Critical issues (${criticals.length})`)
    lines.push(``)
    lines.push(`These must be fixed before adding new features or exposing this codebase to AI-native IDEs.`)
    lines.push(``)
    for (const f of criticals) {
      lines.push(`### ${f.title}`)
      lines.push(`- **Skill:** ${f.skillId}`)
      lines.push(`- **Category:** ${f.category}`)
      if (f.filePath) lines.push(`- **File:** \`${f.filePath}${f.lineNumber ? `:${f.lineNumber}` : ''}\``)
      lines.push(`- **Detail:** ${f.detail}`)
      if (f.evidence) lines.push(`- **Evidence:** \`${f.evidence}\``)
      lines.push(``)
    }
  }

  if (warnings.length > 0) {
    lines.push(`## 🟡 Warnings (${warnings.length})`)
    lines.push(``)
    for (const f of warnings) {
      lines.push(`### ${f.title}`)
      lines.push(`- **Skill:** ${f.skillId}`)
      if (f.filePath) lines.push(`- **File:** \`${f.filePath}\``)
      lines.push(`- **Detail:** ${f.detail}`)
      lines.push(``)
    }
  }

  lines.push(`## Skill files written`)
  lines.push(``)
  lines.push(`The following skill files have been generated in \`ai-context/skills/\`:`)
  lines.push(``)
  for (const r of results) {
    lines.push(`- \`${r.skillId}.skill.md\` — ${r.findings.length} findings`)
  }
  lines.push(``)
  lines.push(`---`)
  lines.push(`_Generated by [AppProbe](https://github.com/appprobe/appprobe)_`)

  return lines.join('\n')
}

function updateClaudeMd(
  projectPath: string,
  aiContextDir: string,
  skills: SkillMarkdown[]
): void {
  const claudeMdPath = path.join(projectPath, 'CLAUDE.md')
  const appProbeSection = buildClaudeMdSection(aiContextDir, skills, projectPath)

  if (fs.existsSync(claudeMdPath)) {
    let existing = fs.readFileSync(claudeMdPath, 'utf-8')
    // Replace existing AppProbe section if present
    const marker = '<!-- appprobe-start -->'
    const markerEnd = '<!-- appprobe-end -->'
    if (existing.includes(marker)) {
      const startIdx = existing.indexOf(marker)
      const endIdx = existing.indexOf(markerEnd) + markerEnd.length
      existing = existing.slice(0, startIdx) + appProbeSection + existing.slice(endIdx)
    } else {
      existing = existing + '\n\n' + appProbeSection
    }
    fs.writeFileSync(claudeMdPath, existing, 'utf-8')
  } else {
    // Create a new CLAUDE.md
    const content = `# Project context for AI assistants\n\n${appProbeSection}`
    fs.writeFileSync(claudeMdPath, content, 'utf-8')
  }
}

function buildClaudeMdSection(
  aiContextDir: string,
  skills: SkillMarkdown[],
  projectPath: string
): string {
  const relativeDir = path.relative(projectPath, aiContextDir)
  const lines = [
    `<!-- appprobe-start -->`,
    `## AppProbe skill context`,
    ``,
    `This project has been scanned by [AppProbe](https://github.com/appprobe/appprobe).`,
    `The following skill files contain rules, patterns, and known issues for this codebase.`,
    `**Always read these before writing or modifying code in this project.**`,
    ``,
    `| Skill file | Purpose |`,
    `|------------|---------|`,
    ...skills.map(s => `| \`${relativeDir}/${s.filename}\` | ${getSkillPurpose(s.skillId)} |`),
    `| \`${relativeDir}/project-health-report.md\` | Full gap report and health score |`,
    ``,
    `### Quick rules`,
    `- Always check the relevant skill file before touching networking, security, or architecture code`,
    `- Do not introduce new third-party libraries without checking \`third-party.skill.md\``,
    `- All security findings in \`security.skill.md\` are pre-existing — do not make them worse`,
    ``,
    `<!-- appprobe-end -->`,
  ]
  return lines.join('\n')
}

function getSkillPurpose(skillId: string): string {
  const map: Record<string, string> = {
    'service-calling': 'Networking layer rules, patterns, and known issues',
    'third-party': 'SDK inventory, versions, deprecations',
    'code-practices': 'Language idioms, antipatterns to avoid',
    'architecture': 'Architectural pattern, separation of concerns rules',
    'security': 'Security posture, hardcoded secrets, storage rules',
  }
  return map[skillId] ?? skillId
}
